/*
  # AI Trend Favorites

  ## Overview
  Adds a dedicated favorites table for the AI Trend Spots feature. This is
  separate from `ai_favorites` (which stores recommendations generated by the
  AI chat/recommendation flow) so users can keep the two buckets distinct in
  the UI ("AI Recommendations" vs "AI Trends").

  ## New Table
  - `ai_trend_favorites`
    - `id` (uuid, primary key)
    - `user_id` (uuid, references auth.users)
    - `trend_spot_id` (uuid, references ai_trend_spots, cascade)
    - `area_key` (text, denormalized for fast listing)
    - `city_name` (text, denormalized)
    - `name` (text, denormalized snapshot of spot name)
    - `category` (text, denormalized)
    - `address` (text, denormalized)
    - `website_url` (text, denormalized)
    - `source` (text, denormalized - foursquare / google_places)
    - `lat` / `lng` (double precision, denormalized)
    - `trend_score` (numeric, score at time of saving)
    - `created_at` / `updated_at` (timestamptz)

  ## Constraints
  - Unique (user_id, trend_spot_id) so a user cannot double-save the same spot.

  ## Security
  - RLS enabled.
  - Four policies (SELECT / INSERT / UPDATE / DELETE) restricted to the owner
    via `auth.uid() = user_id`.

  ## Notes
  1. Denormalized columns mean the favorite remains readable even if the
     underlying trend spot is later pruned by the weekly refresh.
  2. Foreign key uses `ON DELETE CASCADE` so if a spot is permanently deleted
     the orphaned favorite is cleaned up automatically.
*/

CREATE TABLE IF NOT EXISTS public.ai_trend_favorites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trend_spot_id uuid NOT NULL REFERENCES public.ai_trend_spots(id) ON DELETE CASCADE,
  area_key text NOT NULL DEFAULT '',
  city_name text NOT NULL DEFAULT '',
  name text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '',
  address text NOT NULL DEFAULT '',
  website_url text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT '',
  lat double precision,
  lng double precision,
  trend_score numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_trend_favorites_user_spot_unique UNIQUE (user_id, trend_spot_id)
);

CREATE INDEX IF NOT EXISTS ai_trend_favorites_user_idx
  ON public.ai_trend_favorites(user_id);
CREATE INDEX IF NOT EXISTS ai_trend_favorites_area_idx
  ON public.ai_trend_favorites(area_key);

CREATE OR REPLACE FUNCTION public.set_ai_trend_favorites_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_ai_trend_favorites_updated_at ON public.ai_trend_favorites;
CREATE TRIGGER set_ai_trend_favorites_updated_at
BEFORE UPDATE ON public.ai_trend_favorites
FOR EACH ROW EXECUTE FUNCTION public.set_ai_trend_favorites_updated_at();

ALTER TABLE public.ai_trend_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own ai trend favorites" ON public.ai_trend_favorites;
CREATE POLICY "Users can view own ai trend favorites"
  ON public.ai_trend_favorites
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own ai trend favorites" ON public.ai_trend_favorites;
CREATE POLICY "Users can insert own ai trend favorites"
  ON public.ai_trend_favorites
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own ai trend favorites" ON public.ai_trend_favorites;
CREATE POLICY "Users can update own ai trend favorites"
  ON public.ai_trend_favorites
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own ai trend favorites" ON public.ai_trend_favorites;
CREATE POLICY "Users can delete own ai trend favorites"
  ON public.ai_trend_favorites
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);
